### PR TITLE
DATAMONGO-1637

### PR DESCRIPTION
**Pull request by manindr**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAMONGO).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by manindr** [comment]
i have formatted as per the intellij jar, but still there are some formatting changes. Any idea what should i do?

**Comment by mp911de** [comment]
Thanks for your PR. Streaming of aggregation results is a neat idea to optimize memory usage during processing. 

Turns out the IntelliJ settings cause more formatting differences than using the Eclipse formatter (see https://github.com/spring-projects/spring-data-build/blob/master/etc/ide/eclipse-formatting.xml and https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter). Whitespace changes (stripping trailing whitespaces) causes quite a bit of noise so reading the PR is a hard time.

**Comment by manindr** [comment]
@mp911de Thanks for your response. i formatted using eclipse settings too, but unfortunately there's not much difference. Should i setup the project in Eclipse?

Thank you.

**Comment by mp911de** [comment]
The code format looks much better now. Now only the imports and whitespaces are different. I haven't pushed the import order config file to our build commons repository yet. You can find it here: [spring-projects/spring-data-cassandra/etc/springdata.importorder](https://github.com/spring-projects/spring-data-cassandra/blob/master/etc/springdata.importorder) (Note: Number of classes for `*` import is `10`, number of classes for static `*` import is 1). 

Whitespaces, that are trimmed, won't come back with formatting, that's a manual job to put them back into place. The simplest approach for `MongoOperations.java` might be saving the added signatures, reverting all changes to `MongoOperations.java` and putting the signatures back in place. Right now, `MongoOperations.java` contains more noise than actual changes. Don't worry so much about whitespace changes in the other classes.

**Comment by manindr** [comment]
Hi @mp911de thanks for your time. i've made some formatting changes, it is much better now. thanks for your support.

**Comment by manindr** [comment]
Hi @mp911de Please review this whenever you get time. it would be really helpful. Thank you for your time.

**Comment by mp911de** [comment]
I'll have next week time for a detailed review.

**Comment by mp911de** [comment]
That's an awesome PR. Thanks for the great work. I'll take the PR from here. See also my comment in the ticket.

**Comment by manindr** [comment]
Glad i could contribute. Will try to do the same in future.

**Comment by manindr** [comment]
Thanks for your support.

**Comment by mp911de** [comment]
That's merged and polished for 2.0.

**Pull request closed without merging**
