### PR TITLE
handle map key dollar prefix converter

### PR DESCRIPTION
**Pull request by schosterbarak**
Thank you for proposing a pull request. This template will guide you through the essential steps necessary for a pull request.
Make sure that:

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAMONGO).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).
- [x] You provide your full name and an email address registered with your GitHub account. If you’re a first-time submitter, make sure you have completed the [Contributor’s License Agreement form](https://support.springsource.com/spring_committer_signup).
author: barak schoster
email: schosterbarak@gmail.com

### CODE REVIEW

**Comment by schosterbarak** [comment]
handle jira : [https://jira.spring.io/browse/DATAMONGO-1554](https://jira.spring.io/browse/DATAMONGO-1554)
author: barak schoster
email: schosterbarak@gmail.com

**Comment by mp911de** [comment]
This change is not sufficient for the subject you're describing. See further comments in the [linked ticket](https://jira.spring.io/browse/DATAMONGO-1554).

**Comment by pivotal-issuemaster** [comment]
@schosterbarak Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=427) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by christophstrobl** [comment]
We finally decided to not support this. Thank you.

**Pull request closed without merging**
