### PR TITLE
DATAMONGO-501: Initial push for Tailable Cursor Support (Review Only)

### PR DESCRIPTION
**Pull request by amolnayak311**
This pull request is meant for review purpose only and to demonstrate the prototype developed, and collecting opinions and views about the new feature that is planned to be added to MongoTemplate to tail a capped collection.

Some information about tailable cursors can be found here

http://www.mongodb.org/display/DOCS/Tailable+Cursors

The feature included in mongo template looks like this

``` java
TailingCursorHandle handle = template.tailCollection("SomeTestCappedCollection", "id",
      new TailingCursorDocumentListener() {
          public void processDocument(DBObject doc) {
              //process the doc here
          }
});
```

The first two parameters are the name of the capped collection to be tailed and the increasing key which forms the basis for tailing the collection.
The third parameter is an implementation of  <i>TailingCursorDocumentListener</i> which is the callback interface whose <i>processDocument</i> is invoked when a new document is found at the tail of the collection.

The handle is primarily used to let the invoking process stop the tailing that happens asynchronously.

See <code>MongoTemplateTests</code>  for some test cases written around tailable cursor.

### CODE REVIEW

**Comment by benneq** [comment]
any news on this?

**Comment by matthew-b-payne** [comment]
+1 make this happen

**Comment by mp911de** [comment]
Tailable cursors will (most likely) come with Reactive MongoDB support. The reactive driver comes with its own threading infrastructure and push data down the stream (see https://github.com/spring-projects/spring-data-mongodb/pull/393)

**Comment by pivotal-issuemaster** [comment]
@amolnayak311 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=9) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mp911de** [comment]
Tailable cursors are now part of Reactive MongoDB support hence closing this pull request.

**Pull request closed without merging**
