### PR TITLE
DATAMONGO-1393 fixed validation for Lazy Proxies

### PR DESCRIPTION
**Pull request by sterlp**
https://jira.spring.io/browse/DATAMONGO-1393

Fixing this issue I found another I will create a separate ticket for.

I have signed and agree to the terms of the Spring Individual Contributor
License Agreement.

### CODE REVIEW

**Comment by christophstrobl** [comment]
thanks @puel - can you please add your CLA number as a comment to this PR or [DATAMONGO-1393](https://jira.spring.io/browse/DATAMONGO-1393) so we can take it from here.

**Comment by mp911de** [comment]
Hi @puel, 

I started polishing your contribution until we realized alternative approaches to the issue and the consequences this change draws. I updated and commented the ticket [DATAMONGO-1393](https://jira.spring.io/browse/DATAMONGO-1393).

**Comment by pivotal-issuemaster** [comment]
@sterlp Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=350)!

**Comment by sterlp** [comment]
Paul Sterl added a comment - 04/Apr/16 10:19 AM
Confirmation number is 168220160322083905
https://jira.spring.io/browse/DATAMONGO-1393?focusedCommentId=128420&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-128420

**Comment by mp911de** [comment]
We decided to not implement this functionality as we don't want to leak Proxy-awareness into unrelated support classes.

**Pull request closed without merging**
