### PR TITLE
DATAMONGO-779 : Adding the Mongo JNDI factory class to create MongoTemplate through JNDI

### PR DESCRIPTION
**Pull request by Tirrumala**
This is new class supporting the feature Mongo JNDI factory class to create MongoTemplate through JNDI in J2EE Application Server.

This Factory class creates the MongoTemplate whenever the org.springframework.jndi.JndiObjectFactoryBean  requests for loading the JNDI MongoDB object.

### CODE REVIEW

**Comment by limkinZero** [comment]
+1

**Comment by pivotal-issuemaster** [comment]
@Tirrumala Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=85) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Tirrumala Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=85)!

**Comment by PankajAmbekar** [comment]
@Tirrumala Will this work if your mongo server is started in auth mode?

**Comment by mp911de** [comment]
We decided to not include this pull request as JNDI is no longer a technology that we want to support.

**Pull request closed without merging**
