### PR TITLE
DATAMONGO-2596 - Expose KProperty asString function.

### PR DESCRIPTION
**Pull request by ydemartino**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAMONGO-2596).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ydemartino Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=880)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=880) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ydemartino Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=880)!

**Comment by mp911de** [comment]
Paging @sdeleuze. Care to have a look? Happy to discuss whether that's a direction that makes sense.

**Comment by ydemartino** [comment]
Is there anything more I can do to help with the issue?

**Comment by sdeleuze** [comment]
Hey, sorry the the delay, it kind of make sense but @mp911de what is your thought about [this remark](https://jira.spring.io/browse/DATAMONGO-2596?focusedCommentId=189757&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-189757) ?

**Comment by mp911de** [comment]
It took us quite a while to sort out this issue, mainly because we were looking for a way how to bring together `KProperty` and `KPropertyPath` with a proper API. We now introduced an extension function `KProperty<V>.toPath(): String = asString(this)` that calls the `asString` helper to render single `KProperty` and paths to a property path representation.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
