### PR TITLE
Fix can't correct process the key $slice when the field is DBRef.

### PR DESCRIPTION
**Pull request by hosunrise**

### CODE REVIEW

**Comment by christophstrobl** [comment]
@zhsyourai would you mind adding tests and a little context that show/explain the actual issue. Thanks!

**Comment by pivotal-issuemaster** [comment]
@zhsyourai Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=321) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@zhsyourai Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=321)!

**Comment by zhsyourai** [comment]
@christophstrobl This is a explain why can't correct process https://github.com/zhsyourai/sliceDemo

**Comment by christophstrobl** [comment]
thanks @zhsyourai will have a look.

**Comment by christophstrobl** [comment]
Sorry for the way too long silence. This somehow slipped through. 
The issue seems to be resolved with current versions as the following tests passes.

```java
List<JustSomeType> entities = IntStream.range(1, 21).mapToObj(i -> {
	JustSomeType entity = new JustSomeType();
	entity.setId("id-"+i);
	entity.setValue("v"+i);
	return entity;
}).collect(Collectors.toList());

template.insert(entities, JustSomeType.class);

Root root = new Root();
root.id = "root-1";
root.refList = entities;

template.save(root);

Query query = query(where("id").is(root.getId()));
query.fields().slice("refList", 0, 5);

Root result = template.findOne(query, Root.class);
assertThat(result.getRefList()).containsExactlyElementsOf(entities.subList(0, 5));
```

**Comment by hosunrise** [comment]
It's been so long that this PR is no longer relevant, but the problem seems to have been fixed. It's time to close it. 🎉

**Pull request closed without merging**
