### PR TITLE
Need build QueryDslMongodbQuery from mongoTemplate

### PR DESCRIPTION
**Pull request by Dreampie**
http://stackoverflow.com/questions/39928683/spring-data-mongodbquerydslhow-can-build-query-from-mongotemplate#

### CODE REVIEW

**Comment by olivergierke** [comment]
That's not how we usually work :). Please open a ticket in JIRA first to elaborate on what you're trying to achieve. From a quick glance on your SO question, I suspect there's a way to achieve what you want without exposing more API.

**Comment by Dreampie** [comment]
where is jira？

**Comment by mp911de** [comment]
@Dreampie see here: https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc#quickstart (https://jira.spring.io/browse/DATAMONGO)

**Comment by Dreampie** [comment]
sorry，I can not access this URL

**Comment by Dreampie** [comment]
@olivergierke @mp911de

**Comment by olivergierke** [comment]
Mark posted the links to the trackers above.

**Pull request closed without merging**
