### PR TITLE
DATAMONGO-1220 - Extended GridFS template to provide access to grid f…

### PR DESCRIPTION
**Pull request by terribleherbst**
…ile id

The GridFSInputFile is created within the store method, so I've created a new store method with an
optional input parmatmer id which is applied if to the file before being saved in the database.

### CODE REVIEW

**Comment by sudhavk** [comment]
Does gridfs has access to store the hasmap<String,Object> >16mb to be stored in the mongodb database.

Please let me know the solution for inserting >16 mb hashmap data.

**Comment by pivotal-issuemaster** [comment]
@terribleherbst Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=294) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by terribleherbst** [comment]
License Agreement now signed

**Comment by pivotal-issuemaster** [comment]
@terribleherbst Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=294)!

**Comment by mp911de** [comment]
Closing this issue as the change was introduced with DATAMONGO-625/#842 using a different API approach that doesn't require additional overrides.

**Pull request closed without merging**
