### PR TITLE
DATAMONGO-1836 - Add support to hint in aggregation options.

### PR DESCRIPTION
**Pull request by thekaleidoscope**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAMONGO).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks a lot. Care to add the hint implementation to `ReactiveMongoTemplate.aggregateAndMap(…)` as well?

**Comment by thekaleidoscope** [comment]
@mp911de Hi, Thanks for catching it, Missed it somehow. Pushed the changes.

On an unrelated note, the [code of conduct page](https://github.com/spring-projects/spring-data-build/blob/master/CODE_OF_CONDUCT.adoc) is down.

**Comment by mp911de** [comment]
Thanks for your contribution. We're going to take this pull request from here. The Code of Conduct issue is now resolved.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
