### PR TITLE
Add support of $min and $max update operators

### PR DESCRIPTION
**Pull request by odiszapc**
For some reason `$min` and `$max` are not yet supported. Diff adds two methods into the `org.springframework.data.mongodb.core.query.Update` class. Diff speaks for itslef and works pretty well for me.

### CODE REVIEW

**Comment by odiszapc** [comment]
It's very simple commit. Please let me know does it conform you needs

**Comment by mp911de** [comment]
Thanks @odiszapc for the PR. Would you mind adding some tests and creating a Jira ticket at https://jira.spring.io/browse/DATAMONGO?

Can you please sign, if you haven't done already, the [CLA form](https://support.springsource.com/spring_committer_signup) for `Spring Data Access` with project lead `Oliver Gierke` and add your CLA Number as comment to this issue or the newly created Jira ticket?

**Comment by odiszapc** [comment]
Sure, @mp911de

**Comment by odiszapc** [comment]
@mp911de Added few tests to Update class

**Comment by mp911de** [comment]
Great, I'll take it from here on.

**Comment by odiszapc** [comment]
@mp911de Offtop: what's CLA Number for? Where should I use it and how?

**Comment by mp911de** [comment]
A Contributor License Agreement (CLA) defines the terms under which intellectual property has been contributed to a company/project. With the ICLA (individual contributor) number we keep track that you allowed us to include your contibution. We usually include it in your commit message. You can [read more here](https://en.wikipedia.org/wiki/Contributor_License_Agreement) about CLA.

**Comment by mp911de** [comment]
I pushed your code on our [issue/DATAMONGO-1404](https://github.com/spring-projects/spring-data-mongodb/compare/issue/DATAMONGO-1404) branch as we're about to release Hopper GA in the next day. I need to check with the team whether this change will be included into Hopper GA or the next release after Hopper. Thanks for the great work.

**Comment by odiszapc** [comment]
Thank you, Mark!

**Comment by mp911de** [comment]
That's merged with 83d40da6cdada9da90147d195b7941a9b201ab61

**Comment by christophstrobl** [comment]
merged into master via 8983bd26cee60dea1651a759746bc2fded53d9e9. thanks @odiszapc

**Pull request closed without merging**
