### PR TITLE
DATAMONGO-3831 - Support for Atlas $search aggregation pipeline

### PR DESCRIPTION
**Pull request by divyajnu08**
- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by divyajnu08** [comment]
Hi Mark/Christoph

Please find the PR for the above issue-3831 . Kindly provide review comments / improvements.

Thanks

**Comment by mp911de** [comment]
Thanks a lot. We're currently evaluating where's the best place to host Atlas Search support so it might take us a bit until we can proceed here.

**Comment by divyajnu08** [comment]
Sorry it got closed accidently. I will check and implement the review comments.

**Comment by MarcusSorealheis** [comment]
Any idea on status here?

**Comment by mp911de** [comment]
Thanks everyone for your contributions around Atlas Search. Spring Data has always supported open-source data stores and will continue to do so. With the introduction of commercial-/enterprise-only features to some data stores, we face a conflict between remaining accessible to our open source community and demand from users that would like to consume enterprise features provided by their data store. We cannot resolve this conflict with a satisfactory outcome. Supporting commercial features introduces a series of challenges around licensing, testability. Additionally, each feature imposes additional complexity to our code base that needs to be managed in terms of implementation, maintenance, and support.

We need to draw a line somewhere. We decided to not include support for commercial-only features in Spring Data MongoDB. Spring is built with enabling our users in mind and designed in a way that you can achieve your goal while using Spring. You can use the Atlas Search API directly by specifying the `$search` stage in your code. A concise Lambda-representation could look like:

```java
AggregationOperation $search = context -> {
	Document near = new Document("path", "released")
			.append("origin", Instant.ofEpochMilli(1000L))
			.append("pivot", 7776000000L);
	return new Document("$search", new Document("near", near));
};
Aggregation.newAggregation($search, project("title", "released").andExclude("id"));
```

Alternatively, a more elaborate approach is constructing an API using proper factory classes to generate the search document:

```java
Aggregation.newAggregation(AtlasSearch.$search(TextSearch.text("spring").inPath("season")));

public class AtlasSearch implements AggregationOperation {
	private String indexName;
	private AggregationExpression expression;
	@Override
	public Document toDocument(AggregationOperationContext context) {
		Document $search = new Document();
		if(StringUtils.hasText(indexName)) {
			$search.put("index", indexName);
		}
		$search.putAll(expression.toDocument(context));
		return new Document("$search", $search);
	}
	static AtlasSearch $search(AggregationExpression searchFor) {
		// ...
	}
}
public class TextSearch implements AggregationExpression {
	@Override
	public Document toDocument(AggregationOperationContext context) {
		Document text = new Document();
		text.put("query", "...");
		text.put("path", "...");
		text.put("score", "...");
		// ...
		return new Document("text", text);
	}
	public static TextSearch text(String query) {
		// ...
	}
	public TextSearch inPath(String path) {
		// ...
	}
}
```

**Comment by MarcusSorealheis** [comment]
@mp911de I understand your disposition Mark, however many of our customers using Atlas Search never pay us anything. They are in our free tier and live all over the world. While I cannot represent the goals of MongoDB, **I'm here at MongoDB and leading the product to ensure the long-term viability of Apache Lucene** through securing another corporate sponsor. The kernel of Atlas Search, Lucene, is surely open source and free as in freedom. 

Spring Data will be talking to the convenient API we built and maintain to give more users access to Lucene. On the licensing front, I would be willing to loop in our legal team to provide you some assurance because I feel you risk alienating some notable Spring users with this decision. I also love Spring!

**Pull request closed without merging**
