### PR TITLE
DATAMONGO-1271 Provide read lifecycle events when loading DBRefs

### PR DESCRIPTION
**Pull request by yacota**
The PR was for 1271 initially but then found 1287

### CODE REVIEW

**Comment by yacota** [comment]
BTW my CLA code is 121620150519031801

**Comment by christophstrobl** [comment]
@yacota if created #335 to separate DATAMONGO-1287 (the issue with lazy dbref values in ctor) from DATAMONGO-1271. Once that's solved I'll take care about this one here. Thanks already!

**Comment by yacota** [comment]
@christophstrobl DATAMONGO-1287 was closed a long time ago but DATAMONGO-1271 is still "work in progress". Can I do anything to speed up things?, maybe this feature is finally discarded? ... I would really like to have feedback about it (I know all the team is pretty busy working on new things)

**Comment by yacota** [comment]
While checking the original PR you've seen that in the original PR I assumed that lazy DBRef when used in constructor should be skipped(non resolved), as we discussed in https://jira.spring.io/browse/DATAMONGO-1287 that is not the desired behaviour and resolving them eagerly was preferred. 
But let me point to the issue https://jira.spring.io/browse/DATAMONGO-1332 where because of this and the way MappingMongoConverter uses ObjectPath could cause a StackOverFlow error under certain circumstances
Thanks @christophstrobl

**Comment by christophstrobl** [comment]
@yacota I saw the constructor argument related changes and modified the PR a bit - [here's](https://github.com/spring-projects/spring-data-mongodb/compare/issue/DATAMONGO-1271) issue branch in case you want to have a look before I port the stuff to master.

**Comment by yacota** [comment]
@christophstrobl  to me it's 👍

**Comment by christophstrobl** [comment]
thanks @yacota . Merged via 	d1251c4.

**Comment by yacota** [comment]
You're welcome @christophstrobl

**Pull request closed without merging**
