### PR TITLE
Add annotation ReadPreference

### PR DESCRIPTION
**Pull request by jorgerod**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes: https://github.com/spring-projects/spring-data-mongodb/issues/2971

### CODE REVIEW

**Comment by christophstrobl** [comment]
Thank you @jorgerod for the PR we'll have a closer look asap.

**Comment by christophstrobl** [comment]
Thank you again @jorgerod  for investing time into this feature and creating the PR, which looks very decent 👍 

Things we'd need to consider as well are methods inherited from other repository interfaces like `findAll` if the actual repository interface holds a `ReadPreference` annotation, so that users are not forced to redeclare those in order to get the desired result.

We do feel that fine grained control, like tags, are better suited for usage with the template API/custom repositories, where one has more control over the actual query and its dynamics. Therefore we think they should not surface on the repository level.
However, having support for SpEL expressions, as we have in other places already, might be beneficial as this would allow us to register beans that can serve as ReadPreference suppliers.

**Comment by jorgerod** [comment]
Hi @christophstrobl 

Sorry for the waiting time but I've been quite busy lately.


The changes you propose seem to me to be correct.
I see that you are making progress in this area.

I will follow your progress.

Thank you

**Comment by christophstrobl** [comment]
Thank you again @jorgerod for your contribution! The changes have been merged to the _main_ development line.

**Pull request closed without merging**
