### PR TITLE
Observability with Micrometer & Micrometer Tracing

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by mp911de** [comment]
We should add an integration test (is there a mock `Tracer` implementation) and a bit of documentation regarding the tracing integration.

**Comment by gregturn** [comment]
Where does `MongoTracingRecordingHandler` get wired into everything? I don't see an instance created anywhere but inside test cases.

**Comment by marcingrzejszczak** [comment]
Yes, it will be injected into micrometer#config#timerRecordingHandlers

**Comment by marcingrzejszczak** [comment]
I've updated the code to use the enum based approach to describe metrics and spans. I've added automated docs generation from those sources the outcome of which would be the following doc

image

**Comment by gregturn** [comment]
Resolved via 4c77763cd39abf2a2d7e199778016728b45d79fc

**Pull request closed without merging**
