### PR TITLE
DATAMONGO-2218 - Add support for replaceOne operation in BulkOperations

### PR DESCRIPTION
**Pull request by iqjumps**
About this ticket, (https://jira.spring.io/browse/DATAMONGO-2218)

I add replaceOne() method to BulkOperations

### CODE REVIEW

**Comment by christophstrobl** [comment]
Thank you @iqjumps! LGTM, we'll take if from here. 
Would you mind adding yourself as `@author` (please use latin alphabet) to the modified files. Thanks!

**Comment by iqjumps** [comment]
@christophstrobl 
I added author.
I think it can have additional parameter (boolean upsert), please determine and do polishing.
Thanks!

**Comment by iqjumps** [comment]
@christophstrobl 
In progressing? or do you need anything else?

**Comment by christophstrobl** [comment]
@iqjumps thank you - this one's should go into the next milestone but we've not gotten to it yet.

**Comment by iqjumps** [comment]
@christophstrobl 
Okay, Thank you!

**Comment by christophstrobl** [comment]
Thank you @iqjumps! Merged to master via f3b7ce8.

**Pull request closed without merging**
