### PR TITLE
Prevent java.lang.NullPointerException

### PR DESCRIPTION
**Pull request by eperez**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eperez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=535)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=535) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by olivergierke** [comment]
Please make sure you follow our [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).

**Comment by yinzara** [comment]
Throwing a generic RuntimeException instead of a specific NullPointerException is not helpful.  In fact, NullPointerException is exactly what should be thrown here by its definition.  I may accept an IllegalArgumentException or IllegalStateException, but I think NullPointerException is appropriate.

**Comment by mp911de** [comment]
Closing due to lack of movement. We're not going to merge this change.

@yinzara `IllegalArgumentException`/`IllegalStateException` would be the appropriate exceptions here. `NullPointerException` are thrown by the runtime itself and are rather an indicator for programming bugs and not for argument validation.

**Pull request closed without merging**
