### PR TITLE
DATAMONGO-2390 - Add support for maxTimeMS to AggregationOptions.

### PR DESCRIPTION
**Pull request by christophstrobl**
`maxTimeMS` defines the time limit for the aggregation operation. If not specified or set to zero, operations will not time out.

### CODE REVIEW

**Comment by mp911de** [comment]
That's merged and polished now.

**Comment by michalztk** [comment]
Hi. When will you publish this issue in the official spring version?

**Comment by mp911de** [comment]
Please follow our [release wiki](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Neumann) for the release schedule.

**Comment by michalztk** [comment]
Thanks a lot!

**Pull request closed without merging**
