### PR TITLE
DATAMONGO-1813: new method in GridFsOperations

### PR DESCRIPTION
**Pull request by hlang**
Provide new method in GridFsOperations.
`GridFsResource getResource(com.mongodb.client.gridfs.model.GridFSFile file)`

### CODE REVIEW

**Comment by hlang** [comment]
Any chance that this gets merged?

**Comment by mp911de** [comment]
Care to cleanup the pull request in the sense of rebasing it and squashing commits? There are three merges and we can't apply the pull request this way.

**Comment by hlang** [comment]
I messed this one, i will create a new PR

**Comment by hlang** [comment]
New PR: https://github.com/spring-projects/spring-data-mongodb/pull/543

**Pull request closed without merging**
