### PR TITLE
DATAMONGO-3587 - Support Evaluation Query Operators $expr.

### PR DESCRIPTION
**Pull request by divyajnu08**
- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
Care to rebase your pull request? There are several commits that do not belong into this PR.

**Comment by divyajnu08** [comment]
Hi Mark

The changes I made in MatchOperation were since I thought the now we can create a Criteria using the expression  Criteria.expr(AggregationExpression) that can be passed to match operation existing constructor to create the match operation.
So there is no need to explicitly add an expression field in the MatchOperation class for "$expr" operator since it can be done with criteria itself. So I made the changes. I have removed those and now only changes related to Criteria class are there.

Thanks

**Comment by divyajnu08** [comment]
Accidently it got deleted. Please find the PR for this.

**Comment by divyajnu08** [comment]
I am getting this exception while running tests :

reactor.core.publisher.Operators: 315 - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.mongodb.MongoQueryException: Query failed with error code 175 and error message 'Executor error during getMore :: caused by :: collection dropped. UUID 04904bd5-a18c-4070-b183-51771db3c887' on server 127.0.0.1:27017
Caused by: com.mongodb.MongoQueryException: Query failed with error code 175 and error message 'Executor error during getMore :: caused by :: collection dropped. UUID 04904bd5-a18c-4070-b183-51771db3c887' on server 127.0.0.1:27017

**Comment by christophstrobl** [comment]
Thanks for taking the time to craft the PR and sorry for long radio silence. Unfortunately the expression gets evaluated right away without considering the context the query may be run in. This leads to invalid field references, because the `QueryMapper` considers values prefixed with `$` keywords and will simply go over them. 
I'll close this one in favor of #4316

**Pull request closed without merging**
