### PR TITLE
Implement let, pipeline in $lookup

### PR DESCRIPTION
**Pull request by sangyongchoi**
Hi, i am spring data mongo user.
I found that 'let' and 'pipeline' are not supported.
So I implemented it.
Could you please review this pr?
Thank you 😄 

[related issue](https://github.com/spring-projects/spring-data-mongodb/issues/3322)

### CODE REVIEW

**Comment by christophstrobl** [comment]
Thank you @sangyongchoi for bringing this topic up and taking the time to craft the PR! Care to add yourself as an author to the modified files?

**Comment by sangyongchoi** [comment]
@christophstrobl I have already added to the author.
Is there any additional place to fill out?

**Comment by christophstrobl** [comment]
thanks, seems I must have overlooked it. We'll take it from here :)

**Comment by christophstrobl** [comment]
@sangyongchoi thank you very much for your contribution! Merged to _main_ development line via 83923e0.

**Pull request closed without merging**
