### PR TITLE
DATAMONGO-2138 - Type-safe Kotlin query extension

### PR DESCRIPTION
**Pull request by TjeuKayim**
https://jira.spring.io/browse/DATAMONGO-2138

I'm suggesting to add Kotlin extensions for "type-safe queries". This will prevent typos in field names, and improve the readability of a query.

## New Query Syntax
We can achieve type safe queries with Kotlin's Property References.

```kotlin
mongoOperations.find<Book>(
  Query(Book::name isEqualTo "Moby-Dick")
)
// Nested Properties (i.e. refer to "book.author")
Book::author / Author::name regex "^H"
```

## To-Do
- [x] Discuss changes in type hierarchy: _leave it as is_
- [x] Agree on typed query syntax.
- [x] Implement all `Criteria` features.
- [x] Update documentation.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@TjeuKayim Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=622)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=622) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@TjeuKayim Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=622)!

**Comment by TjeuKayim** [comment]
You’re right. We should change as less Java as possible, and just add Kotlin extensions. I’m just trying to fit the new class `TypedQuery` inside the type hierarchy of `Query`, and it’s not that trivial to find an elegant solution. 
If that fails, we just have to overload methods that use `Query` with `TypedQuery` using Kotlin Extensions.

**Comment by TjeuKayim** [comment]
I am finally convinced that is it better not to change the signature of `Query`. Sometimes, it's hard to let go your idea.

**Comment by TjeuKayim** [comment]
We can also consider 'typed updates'.
```kotlin
operations.updateFirst(Book::name isEqualTo "Moby-Dick", set(Book::price, 11))
```

**Comment by TjeuKayim** [comment]
At first, I wanted to restricts the KProperty to members of the Entity class, but it requires much coding to make that work. Every use of Query as parameter will need an Kotlin extension, and the type parameter should be passed through to Criteria.
Maybe we should keep it simple, and trust the developers to use the right type. The concept of typed queries and updates will be more feasible then.

**Comment by mp911de** [comment]
Let's focus on find operations right now and make sure that we can query properties across the document – basically let's support the same criteria features as we do with the regular `Query`. We can add update operations later on.

**Comment by TjeuKayim** [comment]
This version has typed criteria builder functions for `gt, lt, ne, size, all, gte, lte, mod, nin, isEqualTo and inValues`. They can be chained using `typedCriteria()`.

**Comment by TjeuKayim** [comment]
Let's discuss the syntax for typed queries.

1. The simplest implementation would just use the existing Criteria builder.
    ```kotlin
    Criteria(Book::name).eq("Moby-Dick")
        .and(Book::price).lt(1200)
    ```
    This requires the least coding, just some extension functions for Criteria.

2. We could use infix functions.
    ```kotlin
    criteria(
        Book::name isEqualTo "Moby-Dick",
        Book::price lt 1200
    )
    ```
    This is a very clean and good looking syntax. However, the functions have to be imported. This could led to conflicting function names.

3. Or we use lambdas with receiver.
    ```kotlin
    criteria {
        Book::name isEqualTo "Moby-Dick"
        Book::price lt 1200
    }
    ```
    The lambda's receiver has infix member functions to build typed criteria. The use of those functions will be restricted to the lambda parameter, and you don't need to import them.

What do you think?

**Comment by mp911de** [comment]
API usage should impose as little constraints as possible on client code in terms of technical constraints. Importing functions bears the risk of clashing with existing application code/external code.

Examples 2 and 3 read naturally and if option 2 could clash with other imported functions, then option 3 seems the way to go. Reading criteria within a closure easily associates the `AND` nature of criteria combination. 

We should also consider`OR` queries. Maybe something like:

```kotlin
criteria {
    Book::name isEqualTo "Moby-Dick"
    or {
        Book::price lt 1200
        Book::price gt 240
    }
}
```

**Comment by TjeuKayim** [comment]
Looks nice! I was also imagining such "or" queries.
I will go for option 3 then.

**Comment by TjeuKayim** [comment]
All `Criteria` features are now supported by my `TypedCriteriaBuilder`.
Can you review my code @mp911de?

**Comment by TjeuKayim** [comment]
Thank you for the positive feedback! 😃

**Comment by sdeleuze** [comment]
I will have look Monday asap back for vacation if that timing is ok from a Spring Data release perspective.

**Comment by sdeleuze** [comment]
Thanks @TjeuKayim for this contribution.

I think there are issues in the API design that we need to fix before merging that PR. For example I am wondering if we could improve logical operators since I am not super fond of the following syntax:
```
or(
    { Book::price lt 1200 }
    { Book::price gt 240 }
 )

or({ Book::price lt 1200 })
```
I think the root issue is that the API is not composable (`KProperty` extensions return `Unit`), and I am not sure we need to use lambdas with receiver for that use case, since criteria are built from a `KProperty` (they are usually used to propose a set of top level functions to the developer via autocomplete).

What about just using `KProperty` extensions that returns `Criteria` and modify `or` and `and` to be `infix` extensions of `Criteria` is order to allow to translate
```
Criteria("title").isEqualTo("Moby-Dick")
    .orOperator(Criteria("price").lt(1200), Criteria("price").gt(240))
```

To `(Book::title isEqualTo "Moby-Dick") or (Book::price lt 1200 and Book::price.gt 240)`

That seems closer to the Java API principle, while leveraging Kotlin capabilities to provide a more readable syntax.

Any thought?

**Comment by odrotbohm** [comment]
I don't think the two statements are the same. This:

```java
Criteria("title").isEqualTo("Moby-Dick")
    .orOperator(Criteria("price").lt(1200), Criteria("price").gt(240));
```
 is probably meant to be:

```kt
(Book::title isEqualTo "Moby-Dick") and (Book::price lt 1200 or Book::price.gt 240)
```

Note the swapped `and` and `or`.

**Comment by TjeuKayim** [comment]
Let's use top level functions then, like before bc12a92e7c6bdcd87a800ed49c1c2a020201383a.
The builder functions will return a `TypedCriteria` object that stores the operation and lazily implements CriteriaDefinition.

**Comment by TjeuKayim** [comment]
I did a quick refactor to change the syntax.
```kotlin
mongoOperations.find<Book>(Query(
  Book::name isEqualTo "Moby-Dick"
))
typedCriteria(
  Book::name isEqualTo "Moby-Dick",
  orOperator(
    Book::price lt 1200,
    Book::price gt 240
  )
)
```

**Comment by TjeuKayim** [comment]
I think these expressions should match:
```kotlin
(Book::title isEqualTo "Moby-Dick") and ((Book::price lt 1200) or (Book::price gt 240))

Criteria().andOperator(
	Criteria("title").isEqualTo("Moby-Dick"),
	Criteria().orOperator(Criteria("price").lt(1200), Criteria("price").gt(240))
)
```

**Comment by mp911de** [comment]
`andOperator` adds another indirection, so combination through `AND` on the top-level should reflect

```
Criteria("title").isEqualTo("Moby-Dick")
    .orOperator(Criteria("price").lt(1200), Criteria("price").gt(240));
```

`andOperator` is useful when specifying constraints for the same field multiple times (e.g. `{ price: { $ne: 1.99 } }, { price: { $exists: true } } ] }`)

**Comment by sdeleuze** [comment]
@TjeuKayim Do you think it could be possible to make `KProperty` extensions directly return `Criteria` instances and remove `TypedCriteria` and `typedCriteria()` and `typedQuery()`?

**Comment by TjeuKayim** [comment]
I'll try to do that.

**Comment by sdeleuze** [comment]
Indeed I am not a Spring Data MongoDB guru, but it seems the ability to merge 2 `Criteria` would allow Kotlin extensions to be implemented with a much cleaner design. The additional API could be package private if we want to restrict usage to Kotlin extension.

@TjeuKayim In that commit, I have removed usage of `chainCriteria`, if that's ok for you you can maybe integrte it in your PR. https://github.com/sdeleuze/spring-data-mongodb/commit/d591845e7ccbc81420b413b254734e22e86664b7

My WIP commit for removing `TypeCriteria` class is https://github.com/sdeleuze/spring-data-mongodb/commit/f20d042810c100695037f4beb479c980991bab6f, but I would like to have Spring Data team feedback before spending more time on that.

**Comment by TjeuKayim** [comment]
I tried to make `registerCriteriaChainElement()` internal, so that it can be used to implement `and()`.
In simple cases, this works. But the more complex tests fail. I'm not sure why.

**Comment by mp911de** [comment]
I'll have a look tomorrow why the tests fail.

**Comment by mp911de** [comment]
Tests errors originate from the assumption that `Criteria` is hierarchical/resolves criteria recursively for nested criteria paths. `Criteria.getCriteriaObject()` only considers a single level of criteria chain. Elements in the criteria chain are assumed to be singular (i.e. no further hierarchical resolution of a chain but resolution of singular criteria).

I've got the impression that all basic operators (except `$or`, `$nor`, `$and`) are well covered and the syntax reads quite natural. We get additional complexity when trying to sneak in `orOperator` as we lack a common syntax to express this intent.

I played a bit with various options and I feel that we need to discuss the more complex syntax before we decide on it.

So far, I was able to come up with the following options:

```
val typed = (Book::title isEqualTo "Moby-Dick") or (Book::price lt 1200) or (Book::price gt 240)

val typed = (Book::title isEqualTo "Moby-Dick") .orAnyOf ((Book::price lt 1200), (Book::price gt 240))
```

I suggest to:
1. Merge a subset of the changes we've seen so far and produce some documentation.
2. Create a follow-up ticket to support `$or`, `$nor`, `$and` properly and remove `$or`, `$nor`, `$and` support from this PR in preparation for a merge.
3. Discuss and agree on a syntax for  `$or`, `$nor`, `$and`.
4. Implement  `$or`, `$nor`, `$and` support in a separate PR.

Does this make sense?

**Comment by TjeuKayim** [comment]
I've got a new idea. What if we stick more to the original Criteria syntax. So instead of KProperty extensions, we can make new `where()` and `and()` functions that take a KPropery and delegate to their Java counterpart. Other methods of criteria can be extended with infix Kotlin functions.

For example:
```kotlin
where Book::name isEqualTo "Moby-Dick"
  and Book::price lt 1200

where("name").isEqualTo("Moby-Dick")
  .and("price ").lt(1200)
```

This will be much easier to implement, and `Criteria.java` can stay the same.

**Comment by TjeuKayim** [comment]
I've got a new idea. What if we stick more to the original Criteria syntax. So instead of KProperty extensions, we can make new `where()` and `and()` functions that take a KPropery and delegate to their Java counterpart. Other methods of criteria can be extended with infix Kotlin functions.

For example:
```kotlin
where Book::name isEqualTo "Moby-Dick"
  and Book::price lt 1200

where("name").isEqualTo("Moby-Dick")
  .and("price ").lt(1200)
```

This will be much easier to implement, and `Criteria.java` can stay the same.

**Comment by TjeuKayim** [comment]
I've got a new idea. What if we stick more to the original Criteria syntax. So instead of KProperty extensions, we can make new `where()` and `and()` functions that take a KPropery and delegate to their Java counterpart. Other methods of criteria can be extended with infix Kotlin functions.

For example:
```kotlin
where Book::name isEqualTo "Moby-Dick"
  and Book::price lt 1200

where("name").isEqualTo("Moby-Dick")
  .and("price ").lt(1200)
```

This will be much easier to implement, and `Criteria.java` can stay the same.

**Comment by TjeuKayim** [comment]
I've got a new idea. What if we stick more to the original Criteria syntax. So instead of KProperty extensions, we can make new `where()` and `and()` functions that take a KPropery and delegate to their Java counterpart. Other methods of criteria can be extended with infix Kotlin functions.

For example:
```kotlin
where Book::name isEqualTo "Moby-Dick"
  and Book::price lt 1200

where("name").isEqualTo("Moby-Dick")
  .and("price ").lt(1200)
```

This will be much easier to implement, and `Criteria.java` can stay the same.

**Comment by TjeuKayim** [comment]
> Merge a subset of the changes we've seen so far and produce some documentation.

That's probably a good idea.
This feature request is for typed queries. So instead of plain strings, this pull request should add extensions to use Kotlin's Property references. Support for nested properties is needed. Also some extensions to use it within the Criteria builder (`where(KProperty)` & `Criteria.and(KProperty)`.
I will push a new version with just those changes, and later create a follow-up ticket.

**Comment by mp911de** [comment]
> I've got a new idea. What if we stick more to the original Criteria syntax. So instead of KProperty extensions, we can make new where() and and() functions that take a KPropery and delegate to their Java counterpart. Other methods of criteria can be extended with infix Kotlin functions.

We should stick to `(Book::title isEqualTo "Moby-Dick") and (Book::price lt 1200)`. 
The proposed `where(Book::name) isEqualTo "Moby-Dick" and Book::price lt 1200` format is less consistent and less readable.

**Comment by sdeleuze** [comment]
@mp911de I agree with your last comment and your proposal to deal with that in 2 steps.

**Comment by sdeleuze** [comment]
@TjeuKayim Please ping me when I can review the PR updated according to @mp911de feedback, I would like to have a look before the merge.

**Comment by TjeuKayim** [comment]
@sdeleuze, you can review the PR if you like.
I also squashed my commits.

How can you set asciidoctor's output to HTML? (I'm using the Maven plugin)

**Comment by mp911de** [comment]
> How can you set asciidoctor's output to HTML? (I'm using the Maven plugin)

Not sure I follow. Do you want to generate the reference documentation? If so, then run Maven with the `distribute` profile in the project root:

```
$ mvn install -Pdistribute
```

You can find the generated documentation in `target/site/reference/html/index.html`.

**Comment by TjeuKayim** [comment]
Yes, I wanted to generate the reference documentation, but used the wrong maven command. With the distribute profile, it’s working. Thank you helping.

Where should I add the documentation for this feature? I was thinking of a new subheading below “[Additional Query Options](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.query.additional-query-options)”, and calling it “Typed Queries for Kotlin”.

**Comment by sdeleuze** [comment]
Thanks @TjeuKayim, the latest commit is ok for me.

**Comment by mp911de** [comment]
Awesome work @TjeuKayim. Let's move `Typed Queries with Kotlin` directly after `Fluent Template API`. We will do the final review tomorrow and merge your changes to `master` so it can be shipped with Moore M1.

**Comment by TjeuKayim** [comment]
Great tot hear that 😁. I will be available tomorrow from about 11:00 CET.

**Comment by TjeuKayim** [comment]
I placed the documentation after `Fluent Template API`.

**Comment by mp911de** [comment]
That's merged and polished now. Thanks a lot for this excellent pull request.

**Pull request closed without merging**
