### PR TITLE
DATAMONGO-1141 - Add support for $push $sort in Update.

### PR DESCRIPTION
**Pull request by pavelvodrazka**
Sorting update modifiers added. DocumentSort for sorting arrays by document fields and ValueSort for sorting arrays by element values.

### CODE REVIEW

**Comment by pavelvodrazka** [comment]
Or I can refactor it into a single modifier with one constructor accepting Sort and another accepting Direction, if you find it more appropriate.

**Comment by mp911de** [comment]
Hi @pavelvodrazka, thanks for this PR. The code looks pretty decent. Have you signed the [CLA](https://cla.pivotal.io/sign/spring)? 

Having one `SortModifier` class instead of three classes is sufficient. We're heading towards a release tomorrow. It would be great if you find some chance to change the PR otherwise I can take the PR from here and apply the refactoring.

**Comment by pavelvodrazka** [comment]
Hi Mark, thanks for review. Yes, I have signed the CLA.

I'm going to refactor my changes and submit new PR in few minutes.

**Comment by pavelvodrazka** [comment]
I have pushed refactored modifier. Please revise.

**Comment by mp911de** [comment]
Thanks a lot. I'll take the PR from here.

**Comment by olivergierke** [comment]
That's polished, merged and forward-ported.

**Comment by barbakini** [comment]
Hi,
Where can I find an example for this new push and sort functionality. I couldn't find any. Sorry for commenting here. After an answer ı will delete it :)

**Comment by barbakini** [comment]
Hi @olivergierke ,

Where can find tests or an example of this request? Sorry for commenting here. I will delete it after response :)

**Pull request closed without merging**
