### PR TITLE
DATAMONGO-2215 - Add support for array filters to Update.

### PR DESCRIPTION
**Pull request by christophstrobl**
We now support filtered positional `$[<identifier>]` operator via `Updates`. This allows to specify a filter criteria chain for the elements in an array.

```java
new Update()
    .set("grades.$[element]", 100)
    .filterArray(Criteria.where("element").gte(100));
```
----

Depends on: #653 ([DATAMONGO-2054](https://jira.spring.io/browse/DATAMONGO-2054))

### CODE REVIEW

**Comment by mp911de** [comment]
That's merged and polished now.

**Comment by SaravananParamasivan** [comment]
not able to use arrayFilters with update

**Comment by SaravananParamasivan** [comment]
getting error like add cast to receiver

**Comment by aleboulanger** [comment]
@mp911de 
Any possibility to have a report to Spring Data 1.x ?

**Comment by mp911de** [comment]
We do not backport features, also the change is not compatible because 1.x uses the DBObject API. 1.x goes end of life in August. Please upgrade to the 2.x line.

**Comment by aleboulanger** [comment]
thank you @mp911de. 
is it possible, in the mean time, to make a native query with the @Query annotation for example on the spring data repository method ?

**Comment by mp911de** [comment]
No. Native queries (command documents) are assembled by the driver depending on the functionality that should be used. We're using a higher-level API to invoke e.g. find operations instead of using the `execute` functionality.

**Comment by vruddhishah** [comment]
How can I use this dependency with spring boot 2.1.4.Release, As soon as I add this jar via maven shaded plugin, It shows me other errors where it is not able to fetch something from org.springframework.data.*

**Comment by Panksnazi** [comment]
Can we use two identifiers with this change. If yes how to write equivalent spring-data-mongodb query for the below query:
db.animals.update(
                {"animalID":"1234"}, 
                { $set:{"species.$[element].subspecies.$[subspecies].spieceName","German Shepard"}},
                { arrayFilters : [{"element.speciesID":"1"},{"subspecies.subspeciesID":"1"} ] } 
                )

**Comment by vruddhishah** [comment]
@Panksnazi using Update Options
Ref : https://stackoverflow.com/questions/51225487/how-to-use-updateoption-with-arrayfilters-in-spring-data-mongodb/51230648

**Comment by Panksnazi** [comment]
@vruddhishah  I am using spring-boot 2.2.0.M4 , I am looking into using <identifier> which I believe was added as mentioned by christophstrobl.  For more details, please refer the below link

https://stackoverflow.com/questions/57345850/adding-multiple-identifier-in-filterarray-to-update-a-field-in-nested-subdocu

**Comment by vruddhishah** [comment]
> Can we use two identifiers with this change. If yes how to write equivalent spring-data-mongodb query for the below query:
> db.animals.update(
> {"animalID":"1234"},
> { $set:{"species.$[element].subspecies.$[subspecies].spieceName","German Shepard"}},
> { arrayFilters : [{"element.speciesID":"1"},{"subspecies.subspeciesID":"1"} ] }
> )

As per your question, it seemed like you are searching for equivalent spring-data-mongodb query. Hence the relevant reference link was provided. But after the additional information provided, I understand your question now!! Thanks

**Comment by caryfang** [comment]
spring-data-mongodb 2.2.1版本以下的，可以使用BasicBSONObject里的基础方法来支持filterArray方法：

`/**
 * User: fangchao
 * Date: 2023/1/12
 * Time: 14:40
 */
@Getter
@AllArgsConstructor
public enum MongoUpdateOperator {
  INC("$inc"),
  SET("$set");

  String code;
}

/**
 * User: fangchao
 * Date: 2023/1/12
 * Time: 20:45
 */
@Component
public class MongoToolUtils {

  /**
   * 更新mongo表内嵌数组指定元素
   *
   * spring-data-mongodb 2.2.1版本才支持的写法：
   * mongoTemplate.updateMulti(
   * Query.query(criteria),
   * Update.update(
   * updateKey_prefix + "$[elem].shop.shopName",
   * sampleShopDTO.getShopName())
   * .filterArray(Criteria.where("elem.shop.shopId").is(sampleShopDTO.getShopId())),
   * entityClass);
   *
   * 为了弥补spring-data-mongodb低版本没有Update().filterArray方法
   * 这里采用原生mongo语法来执行：
   *
   * @param mongoTemplate
   * @param tabName   更新的文档表名
   * @param query     更新的文档查询条件
   * @param arrayName 更新的内嵌数组名
   * @param updateMap 对内嵌数组元素不同操作的更新map
   * @param eleFilter 更新内嵌数组元素的过滤条件
   * @return
   */
  public static UpdateResult updateMongoArrayElement(
      MongoTemplate mongoTemplate,
      String tabName,
      Criteria query,
      String arrayName,
      Map<MongoUpdateOperator, JSONObject> updateMap,
      Criteria eleFilter){
    BasicDBObject update = new BasicDBObject();
    UpdateOptions updateOptions = new UpdateOptions();

    // 设置$set和$inc等操作符对应的元素更新
    for (MongoUpdateOperator operator : updateMap.keySet()){
      BasicBSONObject eleSetBson = new BasicBSONObject();
      JSONObject eleSetJson = updateMap.get(operator);
      for (String key : eleSetJson.keySet()){
        eleSetBson.put(arrayName.concat(".$[item].").concat(key), eleSetJson.get(key));
      }
      update.put(operator.getCode(), eleSetBson);
    }

    // 组装arrayFilters过滤内容
    BasicDBObject eleFilterBson = new BasicDBObject();
    Document filter = eleFilter.getCriteriaObject();
    for (String key : filter.keySet()){
      eleFilterBson.put("item.".concat(key), filter.get(key));
    }
    updateOptions.arrayFilters(Lists.newArrayList(eleFilterBson));
    return mongoTemplate.getCollection(tabName).updateMany(
        query.getCriteriaObject(),
        update,
        updateOptions
    );
  }

  /**
   * pojo对象转为Document对象,才能被原生BasicBSONObject对象使用
   * 原因见链接 http://mongodb.github.io/mongo-java-driver/3.0/bson/documents/
   * @param pojo
   * @return Document
   */
  public static Document pojoToDoc(Object pojo){
    Document doc = new Document();

    BeanMap beanMap = BeanMap.create(pojo);
    for (Object object : beanMap.entrySet()) {
      if (object instanceof Map.Entry) {
        Map.Entry<String , Object> entry = (Map.Entry<String, Object>)object ;
        String key = entry.getKey();
        doc.put(key, beanMap.get(key));
      }
    }

    return doc;
  }
}`

**Comment by christophstrobl** [comment]
@caryfang if there's an issue related to this ticket please care to open a new one and please do spend some time describing it. Ideally take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.
Given the mentioned version (2.2.1) is out of support since Sept. 2020 you may also try upgrading to a more recent one.

**Pull request closed without merging**
