### PR TITLE
Build a MongoDB 5.0.0 container.

### PR DESCRIPTION
**Pull request by gregturn**
MongoDB has alpha releases in a slightly different location on their distribution server. And they use different keys for signing these alpha releases compared to the overall package listing.

### CODE REVIEW

**Comment by gregturn** [comment]
@christophstrobl this doesn't fix JDK 16 issues, but at least gets the MongoDB 5.0.0 container out of a ditch and operational.

When you merge this into your own branch, the "changes" to the `Dockerfile` should drive Jenkins to build a fresh container for Docker Hub.

**Comment by mp911de** [comment]
On hold until the final MongoDB 5.0 release.

**Comment by christophstrobl** [comment]
@gregturn I think we can continue with this now - MongoDB 5.0 has been released.

**Comment by christophstrobl** [comment]
closed via: #3753

**Pull request closed without merging**
