### PR TITLE
Generate proxy and register reflection for default sorting during AOT.

### PR DESCRIPTION
**Pull request by christophstrobl**
This PR makes sure to generate required cglib proxies during AOT phase so they are ready to use within a native image. Prior to this change default sorting raised an error as class generation is not allowed in a GraalVM native image.

Resolves: #4744

### CODE REVIEW

**Comment by mp911de** [comment]
Why do we even have the need for proxying the Query class? In all other places where we amend the query, we do this via proper methods. Did we consider (or why did we reject) something like `query.getSortObjectOr(() -> Document.parse(method.getAnnotatedSort()))`?

**Comment by christophstrobl** [comment]
Some years back (when GraalVM had not released) using proxies allowed to sneak in the default sorting without changing the original sort object. Without changing internals there's no other way to support the arrangement for previous versions. Going forward it makes sense to work on a solution that can do without it.

**Comment by mp911de** [comment]
That's merged and backported now. For `4.4.x`, we replaced query proxying with a proper query copy.

**Comment by slowbreathing** [comment]
Getting the same error for spring-boot-starter-data-mongodb-reactive

**Comment by christophstrobl** [comment]
@slowbreathing would you mind opening a new ticket providing a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by slowbreathing** [comment]
@christophstrobl Done that. https://github.com/spring-projects/spring-data-mongodb/issues/4900

**Pull request closed without merging**
