### PR TITLE
DATAMONGO-440 - implemented cascade operations on @DBRef fields 

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
Pull request contains implementation of cascading operations: save and delete on fields annotated with @DBRef. Implementation details:
- added new event: AfterDeleteEvent invoked in MongoTemplate after successful object removal
- added @DBRef#cascadeType property
- added CascadingMongoEventListener that intercepts objects before they are converted for save operation and before they are deleted for delete operation if appropriate @DBRef#cascadeType is set.
- in order to emit AfterDeleteEvent MongoOperations#remove methods had to be generified

This implementation is inspired by my research about cascading in Spring Data MongoDB described on blog: http://maciejwalkowiak.pl/blog/2012/04/30/spring-data-mongodb-cascade-save-on-dbref-objects/ where i found that it can be done now by implementing custom event listener but without internal framework changes its a little bit hacky (used reflection instead of Spring Data persistent-entity-like classes, additional annotation, impossible to implement cascading on delete).

If you like this idea and you have suggestions how this implementation can be improved i would be happy to make appropriate changes

### CODE REVIEW

**Comment by Loki-Afro** [comment]
+1

**Comment by chembohuang** [comment]
+1

**Comment by xiaolongyuan** [comment]
+1024

**Comment by Chumper** [comment]
:+1:

**Comment by milehimikey** [comment]
+1

**Comment by timbrauser** [comment]
+1

**Comment by huangered** [comment]
+1

**Comment by aleuchanka** [comment]
+1

**Comment by odiszapc** [comment]
+1

**Comment by maciejwalkowiak** [comment]
Apologies to all who requested this feature, but I am closing it without merging for two reasons:

- it has never been finished. It took me a while before I found time for adding requested fix for handling cyclic references, but it was anyway too late - some internal things have changed (like `AfterDeleteEvent` added in another pull request, incompatible with what I made) making this pull request impossible to merge.
- it wasn't good idea anyway. I realised it after a while, but if you need cascades for Mongo, there is a high chance that something is wrong with design (there was with mine).

If you are not convinced and you would like to pick up my branch, rebase against master and fix everything what's broken - go for it, but I suggest to discuss it first with Spring Data team.

**Pull request closed without merging**
