### PR TITLE
Updated to latest spring-data-mongodb versions

### PR DESCRIPTION
**Pull request by rajadileepkolli**
Bumped to latest versions available manually, Is there any other alternative way where we can update automatically when release versions and snapshot versions are available? 

I feel this should be automated

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks @rajadileepkolli 
Github read-me's are static content. Most Spring Projects do not include versions in their readme files. The current versions are maintained on the project sites itself (see http://projects.spring.io/spring-data-mongodb/). I'll discuss that item with our team.

**Comment by rajadileepkolli** [comment]
Thanks @mp911de , 
I will wait for your update

**Comment by mp911de** [comment]
We're looking forward to adding version badges. Until then we'll stick to updating the `readme.md`.

**Comment by mp911de** [comment]
That's merged with 	1226829.

**Pull request closed without merging**
