### PR TITLE
DATAMONGO-1737 - Fix regression on property order

### PR DESCRIPTION
**Pull request by jbordeau**
Fix regression on property order

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jbordeau Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=482)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=482) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jbordeau Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-mongodb&pullRequestId=482)!

**Comment by olivergierke** [comment]
Care to elaborate on the change? The referenced ticket has been fixed quite some time ago. If you think there's stuff unfixed and still needs to be fixed, please open a new ticket to describe the 

The suggested changes seem to be littered with reformattings which means it's hard to see what has actually changed. Also, the test case uses a lot of mocking and poking into internals. I wonder if just declaring a class with the expected field ordering and then looking up the `PersistentEntity` from the `MongoMappingContext` is closer to actual code being executed.

**Comment by jbordeau** [comment]
In fact, this feature seems to have never been patched according to the history. The test come from [spring-data-common](https://github.com/spring-projects/spring-data-commons/blob/master/src/test/java/org/springframework/data/mapping/model/BasicPersistentEntityUnitTests.java).

The fix only consist of calling super.verify in order to sort the properties.

About the formatting, I applied the provided recommandations and the files configurations. There is a formatting problem on BasicPersistentEntity. I should have commit the formatting in another commit.

**Comment by olivergierke** [comment]
Can you please file a new ticket so that we don't commit against a ticket already contained in release notes of already released versions?

**Comment by jbordeau** [comment]
this is the [new ticket](https://jira.spring.io/browse/DATAMONGO-1737).
I changed my commit message

**Comment by olivergierke** [comment]
Looks like the PR doesn't apply cleanly to master anymore. Would you mind rebasing it?

**Comment by jbordeau** [comment]
it is done.

**Comment by christophstrobl** [comment]
The issue (#2643) had been resolve quite some time ago (Nov. 2017 - via eb51828d) but the PR was never closed.

**Pull request closed without merging**
