### PR TITLE
Add an option to @Field annotation to control property write rules

### PR DESCRIPTION
**Pull request by divyajnu08**
…on write

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by divyajnu08** [comment]
Hi Christoph/Mark 

Please find the pull request , I hope it solves the issue , kindly let me know if any comments.
Also I could find only one test case , could you please guide me what are the other test cases need to be changed ?

Thanks

**Comment by mp911de** [comment]
Thanks for your pull request. It goes already in the right direction. 

Looking at the code, I'm wondering whether it would actually make sense to represent `null` handling with an enumeration. `omitNull` is a negation of what should happen when writing values and from a wording perspective, I don't have a much more descriptive attribute name that would resolve to `boolean`. 

I suggest expressing what should happen if the value is `null` along the lines of `@Field(write=ALWAYS|NON_NULL)` accompanied with an enum `Field.Write {ALWAYS,NON_NULL}` defaulting to `NON_NULL`. Anything else (omitNull, onNull) could be viewed from both sides, if the property is `null` or the field in the document is `null`/non-existent.

**Comment by divyajnu08** [comment]
Hi Mark 

Kindly find the review comments changes updated on the branch.
Let me know if any other change needs to be done.

Thanks

**Comment by mp911de** [comment]
Thanks a lot. I pushed a polished variant of the changes to https://github.com/spring-projects/spring-data-mongodb/tree/issue/3407

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
