### PR TITLE
DATAMONGO-1418 New $out operator for the aggregation framework.

### PR DESCRIPTION
**Pull request by nikolaikopernik**
New [$out](https://docs.mongodb.org/manual/reference/operator/aggregation/out/) aggregation operation.

### CODE REVIEW

**Comment by nikolaikopernik** [comment]
One problem with accepting ICA - I don't know the project's owner's name((

**Comment by mp911de** [comment]
No worries, `Oliver Gierke` is the project lead.

**Comment by nikolaikopernik** [comment]
@mp911de thanks! 
So my ICA confirmation number is **172720160413124705**

**Comment by nikolaikopernik** [comment]
@olivergierke @mp911de  up guys. It's a simple pr

**Comment by mp911de** [comment]
Thanks for your PR. That's merged and polished with f4a5482005ede646dc9222640b924c0f794907ae.

**Pull request closed without merging**
